### ISSUE TITLE
delete site traceback

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#13]
``` python-traceback
127.0.0.1 - - [21/Jul/2015 10:32:07] "POST /admin/site/delete/ HTTP/1.1" 302 -
[2015-07-21 10:32:07,783: ERROR/MainProcess] Task ckan_multisite.task.remove_site_task[2db92a7d-a8a2-4ffa-93f0-6e0aff4a142a] raised unexpected: ValueError('list.remove(x): x not in list',)
Traceback (most recent call last):
  File "/home/ian/boxkite/dcenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ian/boxkite/dcenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ian/boxkite/git/ckan-multisite/ckan_multisite/task.py", line 27, in remove_site_task
    nginx.remove_site(environment.site_name)
  File "/home/ian/boxkite/git/ckan-multisite/ckan_multisite/router.py", line 109, in remove_site
    self.sites.remove(name)
ValueError: list.remove(x): x not in list
```

**Comment by wardi** [comment]
seems to be working now, might have been an unrelated issue
