### ISSUE TITLE
Can't create sites

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#21]
Every effort to create a site ends like such:

```
127.0.0.1 - - [06/Aug/2015 01:12:00] "POST /admin/site/new/?url=%2Fadmin%2Fsite%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1588, in create_view
    model = self.create_model(form)
  File "/home/ubuntu/ckan-multisite-master/ckan_multisite/admin.py", line 35, in create_model
    site = Site(form.name.data)
  File "/home/ubuntu/ckan-multisite-master/ckan_multisite/site.py", line 25, in __init__
    self.environment = Environment.load(MAIN_ENV_NAME, name)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/datacats/environment.py", line 143, in load
    ) = task.load_site(srcdir, datadir, site_name)
  File "/home/ubuntu/ckan-multisite-master/virtualenv/lib/python2.7/site-packages/datacats/task.py", line 242, in load_site
    raise DatacatsError('{} is not a valid site name.'.format(site_name))
DatacatsError: Testing is not a valid site name.
```

**Comment by JackMc** [comment]
Hi there Waldo. 

The particular issue here is that sites may not have names that contain capital letters or certain special characters. This is the make nginx stuff easier. This error should be more obvious, though. I'll look into making it show up on the site itself.

**Comment by waldoj** [comment]
No site names work, including "Test," "Testing," and "Virginia."

**Comment by JackMc** [comment]
The starting capital letter is the problem

**Comment by JackMc** [comment]
Next steps in this project include support of separation between the subdomain and the site name, but currently they are equivalent.

**Comment by JackMc** [comment]
I'm adding site name verification logic as part of my next push.

**Comment by waldoj** [comment]
> The starting capital letter is the problem

Ahh, right. This is why I'm not a software tester. :)
