### ISSUE TITLE
Sed error precedes failed deployment

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#28]
Fresh Ubuntu server, installed from master, ran `run.sh`, and this appeared at the end of the output:

```
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ubuntu

Remember that you will have to log out and back in for this to take effect!

ubuntu ALL=NOPASSWD: /usr/sbin/service nginx reload
sed: -e expression #1, char 29: unknown option to `s'
```

My guess is that this error is why I wasn't told to re-run `./run.sh` to continue the setup process.

**Comment by waldoj** [comment]
After re-running `./run.sh`, after the images are pulled and CKAN etc. is installed, it dies with this:

```
Starting web server at http://127.0.0.1:5402/ ...
+ echo 'You should now be all set up to use CKAN multisite.'
You should now be all set up to use CKAN multisite.
+ redis-server redis.conf
+ trap 'kill 27608' EXIT
+ '[' '' == prod ']'
+ celery -A ckan_multisite.task worker
+ python ckan_multisite/app.py
Traceback (most recent call last):
  File "ckan_multisite/app.py", line 9, in <module>
    from ckan_multisite.api import bp as api_bp
  File "/home/ubuntu/ckan-multisite/ckan_multisite/api.py", line 7, in <module>
    from ckan_multisite.router import DatacatsNginxConfig
  File "/home/ubuntu/ckan-multisite/ckan_multisite/router.py", line 13, in <module>
    from ckan_multisite.config import MAIN_ENV_NAME, DEBUG, PORT
ImportError: cannot import name MAIN_ENV_NAME
+ kill 27608
ubuntu@ip-172-30-0-221:~/ckan-multisite$
```

My guess is that the sed error was an effort to assign `MAIN_ENV_NAME`, which failed, and then couldn't be employed later, but I don't know.

**Comment by JackMc** [comment]
My bad with this.... has to do with certain things not being escaped and then the admin password doesn't get set and it just doesn't go well after that :3

**Comment by JackMc** [comment]
This should all be fixed now in master.

**Comment by waldoj** [comment]
:+1: Works great! What a delightful new setup process.
