### ISSUE TITLE
Error: useradd: UID 0 is not unique

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#35]
New EC2 instance, first install, the second time running `run.sh` (that is, after the permission-necessitated log out / in again):

```
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create multisite -in

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/create.py", line 54, in create
    site_url=opts['--site-url'],
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/create.py", line 91, in create_environment
    fn()
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/environment.py", line 303, in create_ckan_ini
    ro={scripts.get_script_path('run_as_user.sh'): '/scripts/run_as_user.sh'},
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/environment.py", line 833, in run_command
    commit=True, stream_output=stream_output)
  File "/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /usr/lib/ckan/bin/paster make-config ckan /project/development.ini
    Docker Error Log:
    useradd: UID 0 is not unique
```

**Comment by waldoj** [comment]
FWIW, I re-ran `run.sh` and everything started up:

```
+ '[' '!' -e /home/ubuntu/.datacats/multisite ']'
+ redis-server redis.conf
+ trap 'kill 29224' EXIT
+ '[' '' == prod ']'
+ python ckan_multisite/app.py
+ celery -A ckan_multisite.task worker
 * Reloading nginx configuration nginx                                   [ OK ] 
 * Reloading nginx configuration nginx                                   [ OK ] 
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

That doesn't necessarily mean that all is well, but there it is.

**Comment by JackMc** [comment]
CKAN Multisite shouldn't be run as root

**Comment by waldoj** [comment]
Ahh, I hadn't even noticed that I'd prefixed the command with `sudo`! Thanks!
