### ISSUE TITLE
Install fails with virtualenv error

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#38]
New EC2 instance (running Ubuntu), new CKAN Multisite installation, pulling from master. I execute `./run.sh`, it ticks along happily for a while, and terminates like such:

```
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1159, in install_python
    mkdir(lib_dir)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 447, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'virtualenv'
```

Suggestions?

**Comment by wardi** [comment]
@JackMc would you take a look at this?

**Comment by JackMc** [comment]
For sure! I will look at this tomorrow morning.

**Comment by waldoj** [comment]
I tore everything down and started again, leaving me with a slightly different permissions problem in virtualenv. Stepping through the offending bit of `run.sh` manually:

```
# source virtualenv/bin/activate
(virtualenv)# set -xe
(virtualenv)# datacats pull

+ datacats pull
Pulling image datacats/web----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats pull

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/pull.py", line 46, in pull
    retrying_pull_image(i)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/pull.py", line 52, in retrying_pull_image
    "Failed to pull image {}.".format(image_name))
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/pull.py", line 72, in _retry_func
    func(param)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/pull.py", line 83, in pull_image
    for s in pull_stream(image_name):
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/docker.py", line 386, in pull_stream
    return (json.loads(s) for s in _get_docker().pull(image, stream=True))
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/datacats/docker.py", line 98, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/ckan_multisite/virtualenv/local/lib/python2.7/site-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
```

Does "Failed to pull image" indicate that the remote image couldn't be retrieved, perhaps indicating an upstream problem?

**Comment by JackMc** [comment]
Are you running run.sh as root? It should be run as a non-root user.

**Comment by waldoj** [comment]
Nope, not as root.

**Comment by JackMc** [comment]
Okay, I tried this in my VM and it executed fine, but I will attempt when I am in the office tomorrow on an actual EC2 instance

**Comment by mheadd** [comment]
@waldoj - are you just using the default `ubuntu` user on your EC2 instance?

**Comment by waldoj** [comment]
I am.

**Comment by JackMc** [comment]
```
sudo apt-get install git
git clone https://github.com/datacats/ckan-multisite
cd ckan-multisite/
./run.sh 
sudo reboot
./run.sh
sudo reboot
cd ckan-multisite/
 ./run.sh
```

I ran these commands in this sequence and was able to get a running instance of multisite on a t2.small instance (52.32.15.138). Can you try reproducing with these commands?

**Comment by waldoj** [comment]
I'm stepping through this now, but I want to point out that rebooting isn't what `run.sh` calls for:

> you will need to log out and back in from your system

Rebooting now—let's see if that makes a difference.

**Comment by JackMc** [comment]
It shouldn't make a difference, but I did it because of the updates that were applied

**Comment by JackMc** [comment]
(It updated the kernel in the sudo apt-get upgrade part)

**Comment by waldoj** [comment]
I followed your steps, and it died [in the same way as before](https://github.com/datacats/ckan-multisite/issues/38#issuecomment-151900387) at the same point.

**Comment by waldoj** [comment]
Oddly, every time that I run `datacats pull` by hand (as opposed to executing `run.sh`), my SSH connection to the server is immediately severed.

**Comment by waldoj** [comment]
Even `datacats info` fails, generating the same error message (and also severing my SSH connection).

**Comment by wardi** [comment]
That's bizarre. There must be something outside that's killing your session. Is there anything in your system or ssh logs about why the connection is being severed?

**Comment by waldoj** [comment]
There isn't, but I think it's because the disconnect is occurring at the server. It looks like any other log off:

```
----------------------------------------
Connection to opengovdata.net closed.
```

The server's `auth.log` says:

```
Oct 29 17:59:24 ip-172-31-10-119 sshd[1622]: Received disconnect from 123.45.67.89: 11: disconnected by user
Oct 29 17:59:24 ip-172-31-10-119 sshd[1568]: pam_unix(sshd:session): session closed for user ubuntu
```

(My IP is redacted.)

Weird.

**Comment by mheadd** [comment]
@JackMc On your t2.small instance, are you able to change the admin password and log in to a new site?

**Comment by waldoj** [comment]
For the record, I deleted the instance, started from scratch, and now everything works great. ¯_(ツ)_/¯
